"""Beautiful PDF report of a learned context with diagrams and visual formatting.

This module creates a visually stunning PDF export of EPM context data, featuring:
- Professional cover page with logo placeholder
- Clickable table of contents
- Visual architecture diagrams using drawing primitives
- Colored headers and styled tables
- Hierarchy trees with visual connectors
- Bar charts for summary statistics
"""

from __future__ import annotations

from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    Frame, KeepTogether, PageTemplate, Image
)
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, Line, Circle, String
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics import renderPDF
from sqlalchemy.orm import Session

from ..db.models import ContextVersion
from ..services import context_store

PDF_MIME = "application/pdf"

# Color palette matching the app's IBM Carbon design system
COLOR_PRIMARY = colors.HexColor("#4589ff")
COLOR_SUCCESS = colors.HexColor("#42be65")
COLOR_WARNING = colors.HexColor("#ff832b")
COLOR_TEXT_PRIMARY = colors.HexColor("#161616")
COLOR_TEXT_SECONDARY = colors.HexColor("#8d8d8d")
COLOR_BORDER = colors.HexColor("#393939")
COLOR_BG_LIGHT = colors.HexColor("#f9f9f9")


def _sorted_records(records: list, kind: str) -> list:
    """Filter records by kind."""
    return [r for r in records if r.kind == kind]


class NumberedCanvas(canvas.Canvas):
    """Custom canvas for page numbering and footer."""

    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        """Add page number and footer to each page."""
        self.setFont("Helvetica", 8)
        self.setFillColor(COLOR_TEXT_SECONDARY)
        page_num = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(7.5 * inch, 0.5 * inch, page_num)
        self.drawString(1 * inch, 0.5 * inch, "Generated by EPM Wizard")


def _create_styles():
    """Create custom paragraph styles."""
    styles = getSampleStyleSheet()

    # Title style
    styles.add(ParagraphStyle(
        name='CustomTitle',
        parent=styles['Heading1'],
        fontSize=36,
        textColor=COLOR_PRIMARY,
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    ))

    # Subtitle style
    styles.add(ParagraphStyle(
        name='CustomSubtitle',
        parent=styles['Normal'],
        fontSize=18,
        textColor=COLOR_TEXT_SECONDARY,
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica'
    ))

    # Section heading
    styles.add(ParagraphStyle(
        name='SectionHeading',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=COLOR_PRIMARY,
        spaceBefore=20,
        spaceAfter=15,
        fontName='Helvetica-Bold',
        borderWidth=0,
        borderColor=COLOR_PRIMARY,
        borderPadding=5
    ))

    # Subsection heading
    styles.add(ParagraphStyle(
        name='SubsectionHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=COLOR_PRIMARY,
        spaceBefore=15,
        spaceAfter=10,
        fontName='Helvetica-Bold'
    ))

    # Key-value style
    styles.add(ParagraphStyle(
        name='KeyValue',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=6,
        fontName='Helvetica'
    ))

    # Body text
    styles.add(ParagraphStyle(
        name='BodyTextCustom',
        parent=styles['Normal'],
        fontSize=10,
        spaceAfter=8,
        fontName='Helvetica'
    ))

    # Tree style for hierarchies
    styles.add(ParagraphStyle(
        name='TreeNode',
        parent=styles['Normal'],
        fontSize=9,
        fontName='Courier',
        leftIndent=10,
        spaceAfter=1
    ))

    return styles


def _create_cover_page(cv: ContextVersion, styles):
    """Create a beautiful cover page."""
    story = []

    # Add vertical spacing
    story.append(Spacer(1, 2 * inch))

    # Logo placeholder (you can replace with actual logo)
    d = Drawing(100, 100)
    # Create a simple geometric logo placeholder
    d.add(Circle(50, 50, 40, fillColor=COLOR_PRIMARY, strokeColor=COLOR_PRIMARY, strokeWidth=2))
    d.add(Circle(50, 50, 25, fillColor=colors.white, strokeColor=colors.white))
    d.add(Rect(35, 35, 30, 30, fillColor=COLOR_PRIMARY, strokeColor=None))
    story.append(d)

    story.append(Spacer(1, 0.5 * inch))

    # Title
    title = Paragraph("EPM Context Report", styles['CustomTitle'])
    story.append(title)

    # Subtitle - application name
    subtitle = Paragraph(cv.application, styles['CustomSubtitle'])
    story.append(subtitle)

    story.append(Spacer(1, 1 * inch))

    # Metadata box
    metadata_data = [
        ['Context Version:', cv.label],
        ['Environment:', (cv.manifest or {}).get('environmentClassification', '—')],
        ['Generated:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
    ]

    metadata_table = Table(metadata_data, colWidths=[2 * inch, 3 * inch])
    metadata_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('TEXTCOLOR', (0, 0), (0, -1), COLOR_PRIMARY),
        ('TEXTCOLOR', (1, 0), (1, -1), COLOR_TEXT_PRIMARY),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))

    story.append(metadata_table)
    story.append(PageBreak())

    return story


def _create_toc(counts: dict, styles):
    """Create a table of contents with clickable links."""
    story = []

    story.append(Paragraph("Table of Contents", styles['SectionHeading']))
    story.append(Spacer(1, 0.3 * inch))

    toc_data = [
        ['Section', 'Items'],
        ['Summary', '—'],
        ['Cubes', str(counts.get('cubes', 0))],
        ['Dimensions', str(counts.get('dimensions', 0))],
        ['Member Hierarchies', str(counts.get('members', 0))],
        ['Business Rules', str(counts.get('rules', 0))],
        ['Variables', str(counts.get('variables', 0))],
    ]

    toc_table = Table(toc_data, colWidths=[4 * inch, 1.5 * inch])
    toc_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 11),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
    ]))

    story.append(toc_table)
    story.append(PageBreak())

    return story


def _create_summary_chart(counts: dict):
    """Create a bar chart showing summary statistics."""
    drawing = Drawing(400, 200)

    chart = VerticalBarChart()
    chart.x = 50
    chart.y = 50
    chart.height = 125
    chart.width = 300

    # Prepare data
    categories = ['Cubes', 'Dimensions', 'Rules', 'Variables']
    values = [
        counts.get('cubes', 0),
        counts.get('dimensions', 0),
        counts.get('rules', 0),
        counts.get('variables', 0)
    ]

    chart.data = [values]
    chart.categoryAxis.categoryNames = categories
    chart.categoryAxis.labels.fontSize = 9
    chart.valueAxis.labels.fontSize = 9

    # Style the bars with our color palette
    chart.bars[0].fillColor = COLOR_PRIMARY
    chart.bars.strokeColor = COLOR_PRIMARY
    chart.bars.strokeWidth = 0.5

    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueStep = max(1, max(values) // 5) if max(values) > 0 else 1

    drawing.add(chart)

    return drawing


def _create_summary_section(counts: dict, styles):
    """Create the summary section with statistics."""
    story = []

    story.append(Paragraph("Summary", styles['SectionHeading']))
    story.append(Paragraph(
        "Overview of the EPM context contents.",
        styles['BodyTextCustom']
    ))
    story.append(Spacer(1, 0.2 * inch))

    # Add bar chart
    story.append(_create_summary_chart(counts))
    story.append(Spacer(1, 0.3 * inch))

    # Summary table
    table_data = [
        ['Category', 'Count'],
    ]
    for key, value in counts.items():
        table_data.append([key.replace('_', ' ').title(), str(value)])

    summary_table = Table(table_data, colWidths=[4 * inch, 1.5 * inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))

    story.append(summary_table)
    story.append(PageBreak())

    return story


def _create_cube_architecture_diagram(cubes_data: list, dims_data: list):
    """Create visual diagram showing cube-dimension relationships using drawing primitives."""
    # Limit to first 5 cubes for clarity
    display_cubes = cubes_data[:5]

    if not display_cubes:
        return None

    # Calculate dimensions
    cube_width = 120
    cube_height = 30
    dim_width = 100
    dim_height = 20
    h_spacing = 40
    v_spacing = 15

    # Build dimension set
    all_dims = set()
    for cube in display_cubes:
        data = cube.data or {}
        dims = data.get("dimensions") or []
        for dim in dims[:6]:  # Limit dimensions per cube
            all_dims.add(dim)

    dims_list = sorted(all_dims)[:10]  # Limit total dimensions shown

    # Calculate drawing size
    drawing_width = 500
    drawing_height = len(display_cubes) * (cube_height + v_spacing) + 100

    drawing = Drawing(drawing_width, drawing_height)

    # Draw cubes on the left
    cube_y_positions = {}
    y_pos = drawing_height - 50

    for cube in display_cubes:
        # Cube rectangle
        drawing.add(Rect(
            20, y_pos, cube_width, cube_height,
            fillColor=COLOR_PRIMARY,
            strokeColor=COLOR_PRIMARY,
            strokeWidth=2
        ))

        # Cube label
        label = cube.name[:15] + '...' if len(cube.name) > 15 else cube.name
        drawing.add(String(
            25, y_pos + cube_height / 2,
            label,
            fontSize=9,
            fillColor=colors.white,
            fontName='Helvetica-Bold',
            textAnchor='start'
        ))

        cube_y_positions[cube.name] = y_pos + cube_height / 2
        y_pos -= (cube_height + v_spacing)

    # Draw dimensions on the right
    dim_y_positions = {}
    y_pos = drawing_height - 50
    dim_x = drawing_width - dim_width - 20

    for dim in dims_list:
        # Dimension rectangle
        drawing.add(Rect(
            dim_x, y_pos, dim_width, dim_height,
            fillColor=COLOR_SUCCESS,
            strokeColor=COLOR_SUCCESS,
            strokeWidth=1
        ))

        # Dimension label
        label = dim[:12] + '...' if len(dim) > 12 else dim
        drawing.add(String(
            dim_x + 5, y_pos + dim_height / 2,
            label,
            fontSize=8,
            fillColor=colors.white,
            fontName='Helvetica',
            textAnchor='start'
        ))

        dim_y_positions[dim] = y_pos + dim_height / 2
        y_pos -= (dim_height + 10)

    # Draw connecting lines
    for cube in display_cubes:
        data = cube.data or {}
        dims = data.get("dimensions") or []
        cube_y = cube_y_positions[cube.name]

        for dim in dims:
            if dim in dim_y_positions:
                dim_y = dim_y_positions[dim]

                # Draw line from cube to dimension
                drawing.add(Line(
                    20 + cube_width, cube_y,
                    dim_x, dim_y,
                    strokeColor=COLOR_BORDER,
                    strokeWidth=0.5,
                    strokeDashArray=[2, 2]
                ))

    # Add legend
    legend_y = 20
    drawing.add(Rect(20, legend_y, 15, 10, fillColor=COLOR_PRIMARY, strokeColor=None))
    drawing.add(String(40, legend_y + 5, 'Cubes', fontSize=8, fillColor=COLOR_TEXT_PRIMARY))

    drawing.add(Rect(100, legend_y, 15, 10, fillColor=COLOR_SUCCESS, strokeColor=None))
    drawing.add(String(120, legend_y + 5, 'Dimensions', fontSize=8, fillColor=COLOR_TEXT_PRIMARY))

    return drawing


def _create_cubes_section(cubes: list, dims: list, styles):
    """Create the cubes section with architecture diagram."""
    story = []

    story.append(Paragraph(f"Cubes ({len(cubes)})", styles['SectionHeading']))

    # Add architecture diagram
    if cubes and dims:
        story.append(Paragraph("Architecture Diagram", styles['SubsectionHeading']))
        story.append(Paragraph(
            "Visual representation of how dimensions connect to cubes:",
            styles['BodyTextCustom']
        ))
        story.append(Spacer(1, 0.1 * inch))

        diagram = _create_cube_architecture_diagram(cubes, dims)
        if diagram:
            story.append(diagram)
            story.append(Spacer(1, 0.3 * inch))

    # Cubes table
    story.append(Paragraph("Cube Details", styles['SubsectionHeading']))

    table_data = [
        ['Cube', 'Type', '# Dims', 'Dimensions (first 5)'],
    ]

    for cube in cubes:
        data = cube.data or {}
        dims_list = data.get("dimensions") or []
        dim_str = ", ".join(dims_list[:5])
        if len(dims_list) > 5:
            dim_str += f" ... +{len(dims_list) - 5} more"

        table_data.append([
            cube.name,
            data.get("type", ""),
            str(len(dims_list)),
            dim_str
        ])

    cube_table = Table(table_data, colWidths=[1.5 * inch, 1 * inch, 0.7 * inch, 3.3 * inch])
    cube_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (2, 0), (2, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))

    story.append(cube_table)
    story.append(PageBreak())

    return story


def _create_dimensions_section(dims: list, styles):
    """Create the dimensions section."""
    story = []

    story.append(Paragraph(f"Dimensions ({len(dims)})", styles['SectionHeading']))

    table_data = [
        ['Dimension', 'Type', 'Density', 'Used in cubes'],
    ]

    for dim in dims:
        data = dim.data or {}
        cubes = data.get("cubes") or []
        cube_list = ", ".join(cubes[:3])
        if len(cubes) > 3:
            cube_list += f" +{len(cubes) - 3}"

        table_data.append([
            dim.name,
            data.get("type", ""),
            "Dense" if data.get("dense") else "Sparse",
            cube_list
        ])

    dim_table = Table(table_data, colWidths=[2 * inch, 1.2 * inch, 1 * inch, 2.3 * inch])
    dim_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))

    story.append(dim_table)
    story.append(PageBreak())

    return story


def _create_hierarchy_tree_drawing(members: list, max_depth: int = 3):
    """Create a visual tree drawing of member hierarchies."""
    by_name = {m.name: m for m in members}
    children: dict[str | None, list] = {}
    for m in members:
        parent = m.parent if (m.parent and m.parent in by_name and m.parent != m.name) else None
        children.setdefault(parent, []).append(m)

    roots = children.get(None, [])[:2]  # Limit to 2 roots for better layout

    if not roots:
        return None

    # Calculate tree layout with better spacing
    node_height = 25
    node_width = 160
    v_spacing = 30
    indent_per_level = 25

    # Count total visible nodes
    def count_nodes(node, depth):
        if depth >= max_depth:
            return 1
        count = 1
        node_children = children.get(node.name, [])[:4]  # Max 4 children per node
        for child in node_children:
            count += count_nodes(child, depth + 1)
        return count

    total_nodes = sum(count_nodes(root, 0) for root in roots)
    total_height = total_nodes * v_spacing + 40
    drawing = Drawing(500, min(total_height, 450))  # Cap height

    y_cursor = [drawing.height - 30]

    def draw_node(node, depth, parent_x=None, parent_y=None):
        if depth >= max_depth or y_cursor[0] < 20:
            return

        y = y_cursor[0]
        x = 20 + (depth * indent_per_level)
        y_cursor[0] -= v_spacing

        # Choose color based on depth
        if depth == 0:
            box_color = COLOR_PRIMARY
        elif depth == 1:
            box_color = COLOR_SUCCESS
        else:
            box_color = COLOR_TEXT_SECONDARY

        # Draw connecting line from parent
        if parent_x is not None and parent_y is not None:
            drawing.add(Line(
                parent_x + node_width, parent_y + node_height / 2,
                x, y + node_height / 2,
                strokeColor=COLOR_BORDER,
                strokeWidth=0.5,
                strokeDashArray=[2, 2]
            ))

        # Draw node box
        drawing.add(Rect(
            x, y, node_width, node_height,
            fillColor=box_color,
            strokeColor=box_color,
            strokeWidth=1
        ))

        # Node label - truncate long names
        label = node.name[:18] + '...' if len(node.name) > 18 else node.name
        drawing.add(String(
            x + 5, y + node_height / 2,
            label,
            fontSize=8,
            fillColor=colors.white,
            fontName='Helvetica',
            textAnchor='start'
        ))

        # Draw children (max 4)
        node_children = children.get(node.name, [])[:4]
        for child in node_children:
            draw_node(child, depth + 1, x, y)

    # Draw each root
    for root in roots:
        draw_node(root, 0)

    return drawing


def _create_members_section(members: list, styles):
    """Create the member hierarchies section with visual trees."""
    story = []

    story.append(Paragraph(
        f"Member Hierarchies ({len(members)} total)",
        styles['SectionHeading']
    ))

    if not members:
        story.append(Paragraph(
            "No members were captured. Members require an EPM Automate metadata "
            "export or LCM snapshot; run a context refresh once that is configured.",
            styles['BodyTextCustom']
        ))
        story.append(PageBreak())
        return story

    intro_text = (
        "Visual tree representation of dimension members showing parent-child "
        "relationships. Hierarchies are limited to 3 levels for readability."
    )
    story.append(Paragraph(intro_text, styles['BodyTextCustom']))
    story.append(Spacer(1, 0.2 * inch))

    # Group by dimension
    by_dim: dict[str, list] = {}
    for m in members:
        by_dim.setdefault(m.dimension or "—", []).append(m)

    # Show first 6 dimensions with hierarchies
    shown_dims = sorted(by_dim.keys())[:6]

    for dim in shown_dims:
        story.append(Paragraph(
            f"{dim} ({len(by_dim[dim])} members)",
            styles['SubsectionHeading']
        ))

        # Create visual tree
        tree_drawing = _create_hierarchy_tree_drawing(by_dim[dim])
        if tree_drawing:
            story.append(tree_drawing)
            story.append(Spacer(1, 0.2 * inch))

    if len(by_dim) > 6:
        remaining_count = sum(len(by_dim[d]) for d in by_dim if d not in shown_dims)
        story.append(Paragraph(
            f"... and {len(by_dim) - 6} more dimensions not shown ({remaining_count} members total)",
            styles['BodyTextCustom']
        ))

    story.append(PageBreak())

    return story


def _create_rules_section(rules: list, styles):
    """Create the business rules section."""
    story = []

    story.append(Paragraph(f"Business Rules ({len(rules)})", styles['SectionHeading']))

    if not rules:
        story.append(Paragraph("No business rules found.", styles['BodyTextCustom']))
        story.append(PageBreak())
        return story

    story.append(Paragraph(
        "Calculation scripts and business rules defined in the application.",
        styles['BodyTextCustom']
    ))
    story.append(Spacer(1, 0.2 * inch))

    # Create a styled list of rules
    table_data = [['#', 'Rule Name']]

    for idx, rule in enumerate(rules[:50], 1):  # Limit to first 50
        table_data.append([str(idx), rule.name])

    rules_table = Table(table_data, colWidths=[0.5 * inch, 6 * inch])
    rules_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))

    story.append(rules_table)

    if len(rules) > 50:
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(
            f"... and {len(rules) - 50} more rules not shown",
            styles['BodyTextCustom']
        ))

    story.append(PageBreak())

    return story


def _create_variables_section(variables: list, styles):
    """Create the variables section."""
    story = []

    story.append(Paragraph(
        f"Substitution & User Variables ({len(variables)})",
        styles['SectionHeading']
    ))

    if not variables:
        story.append(Paragraph("No variables found.", styles['BodyTextCustom']))
        story.append(PageBreak())
        return story

    story.append(Paragraph(
        "Variables used for dynamic calculations and member substitutions.",
        styles['BodyTextCustom']
    ))
    story.append(Spacer(1, 0.2 * inch))

    table_data = [['Variable', 'Dimension', 'Value']]

    for var in variables:
        data = var.data or {}
        table_data.append([
            var.name,
            data.get("dimension") or "—",
            str(data.get("value") or "—")
        ])

    var_table = Table(table_data, colWidths=[2 * inch, 2 * inch, 2.5 * inch])
    var_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))

    story.append(var_table)
    story.append(PageBreak())

    return story


def build_context_pdf(session: Session, context_version_id: str) -> tuple[str, bytes]:
    """
    Build a beautiful PDF report of the EPM context.

    Args:
        session: Database session
        context_version_id: ID of the context version to export

    Returns:
        Tuple of (filename, pdf_bytes)

    Raises:
        KeyError: If context version not found
    """
    # Fetch data
    cv = session.get(ContextVersion, context_version_id)
    if cv is None:
        raise KeyError("context version not found")

    records = context_store.get_records(session, context_version_id)
    counts = (cv.manifest or {}).get("counts", {})

    # Create PDF
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )

    # Get styles
    styles = _create_styles()

    # Build story
    story = []

    # Cover page
    story.extend(_create_cover_page(cv, styles))

    # Table of contents
    story.extend(_create_toc(counts, styles))

    # Summary
    story.extend(_create_summary_section(counts, styles))

    # Cubes
    cubes = _sorted_records(records, "cube")
    dims = _sorted_records(records, "dimension")
    if cubes:
        story.extend(_create_cubes_section(cubes, dims, styles))

    # Dimensions
    if dims:
        story.extend(_create_dimensions_section(dims, styles))

    # Members
    members = _sorted_records(records, "member")
    story.extend(_create_members_section(members, styles))

    # Rules
    rules = _sorted_records(records, "rule")
    if rules:
        story.extend(_create_rules_section(rules, styles))

    # Variables
    variables = _sorted_records(records, "variable")
    if variables:
        story.extend(_create_variables_section(variables, styles))

    # Build PDF with numbered pages
    doc.build(story, canvasmaker=NumberedCanvas)

    return f"{cv.label}.pdf", buffer.getvalue()
