"""LCM snapshot form-definition parsing tests.

The shipped fixture snapshot carries only navigation-flow form *references*;
richer exports include real definition XML under ``Data Forms``. These tests
build synthetic zips whose definition files are generated by the artifact
renderer itself (``render_xml``), guaranteeing format fidelity with what the
parser round-trips, and prove: parsed FormRecords carry a full ``definition``,
a malformed file degrades to a name-only record plus an issue, nav-flow stubs
never duplicate a parsed definition, and the definition survives the context
merge into ``build_tenant_metadata`` for reference-form cloning.
"""

from __future__ import annotations

import io
import zipfile

from app.agent.form_nlu import build_initial_spec
from app.artifacts.parser import parse_definition
from app.artifacts.renderer import render_xml
from app.context import analyze_snapshot, merge_snapshot_into_context
from app.context import snapshot as snapshot_mod
from app.schemas.form_spec import (
    AxisMember,
    BusinessRuleAssociation,
    FormSpecification,
    MemberSelection,
)
from app.services import context_store
from app.services import projects as projects_svc

_APP = "ACME_PLN"
_HP = f"HP-{_APP}"
_DIMS = f"{_HP}/resource/Global Artifacts/Common Dimensions/Standard Dimensions"
_GLOBAL_FORMS = f"{_HP}/resource/Global Artifacts/Data Forms"
_CUBE_FORMS = f"{_HP}/resource/Cube/Plan1/Data Forms"
_NAV_FLOWS = f"{_HP}/resource/Global Artifacts/Navigation Flows"


# --- synthetic snapshot builder (pattern from test_snapshot_context) -----------


def _dim_csv(dimension: str, rows: list[str], dim_type: str = "None") -> str:
    header_block = (
        "#!-- HEADERBLOCK DIMENSION XML\n"
        '<?xml version="1.0" encoding="UTF-8" ?>\n'
        "<DIMENSIONS>\n"
        f' <Dimension name="{dimension}" density="Sparse" dimensionType="{dim_type}">\n'
        " </Dimension>\n"
        "</DIMENSIONS>\n"
        "#--!\n"
    )
    header = (f"{dimension}, Parent, Alias: Default, Data Storage, Formula, Data Type, UDA,"
              " Smart List, Description, Aggregation (Plan1), Data Storage (Plan1)")
    return "\ufeff" + header_block + header + "\n" + "\n".join(rows) + "\n"


_NAV_FLOW = """<?xml version="1.0" encoding="UTF-8" ?>
 <fuseStructure name="Admin" xmlns="http://xmlns.oracle.com/epm/common/structure" >
 <usageXML><![CDATA[<?xml version = '1.0' encoding = 'UTF-8'?>
<fuseStructureUsage xmlns="http://xmlns.oracle.com/epm/common/structure">
   <categories><category id="X"><card id="C1"><tab id="T1">
      <tfParameters>
         <tfParameter artifactUID="7~~~Rolling Forecast" name="formId" artifactName="Rolling Forecast"/>
         <tfParameter artifactUID="107~~~Summary Dashboard" name="formId" artifactName="Summary Dashboard"/>
      </tfParameters>
   </tab></card></category></categories>
</fuseStructureUsage>]]></usageXML>
</fuseStructure>
"""


def _form_spec(name: str, cube: str = "Plan1") -> FormSpecification:
    return FormSpecification(
        name=name,
        description=f"{name} (snapshot test)",
        application=_APP,
        cube=cube,
        folder="Forecasting",
        pov=[AxisMember(dimension="Scenario", selection=MemberSelection(type="member", member="Forecast"))],
        rows=[AxisMember(dimension="Account",
                         selection=MemberSelection(type="children", member="Account"),
                         suppress_missing=True)],
        columns=[AxisMember(dimension="Period",
                            selection=MemberSelection(type="range", start="Jan", end="Dec"))],
        business_rule_associations=[BusinessRuleAssociation(rule_name="Calc All",
                                                            association_type="runAfterSave")],
    )


def _base_files() -> dict[str, str]:
    return {
        f"{_DIMS}/Account.csv": _dim_csv("Account", [
            "Account,,,,,,,,,,",
            "Salaries,Account,Base Salaries,store data,,currency,,,,+,store data",
        ], dim_type="Account"),
    }


def _zip_bytes(files: dict[str, str]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for path, text in sorted(files.items()):
            zf.writestr(path, text.encode("utf-8"))
    return buf.getvalue()


def _forms(bundle) -> dict[str, dict]:
    return {r["name"]: r for r in bundle.records if r["kind"] == "form"}


# --- definition parsing ---------------------------------------------------------


def test_definition_files_parse_into_full_form_records():
    files = _base_files()
    files[f"{_GLOBAL_FORMS}/Rolling Forecast.xml"] = render_xml(_form_spec("Rolling Forecast"))
    files[f"{_CUBE_FORMS}/Cash Detail.xml"] = render_xml(_form_spec("Cash Detail"))
    bundle = analyze_snapshot(_zip_bytes(files))

    assert bundle.analysis.issues == []
    assert bundle.analysis.counts["forms"] == 2
    forms = _forms(bundle)
    assert set(forms) == {"Rolling Forecast", "Cash Detail"}

    data = forms["Rolling Forecast"]["data"]
    assert data["application"] == _APP
    assert data["cube"] == "Plan1"  # global folder entry: cube taken from the definition
    assert data["source"] == "snapshot"
    assert "referencedOnly" not in data
    definition = data["definition"]
    assert "name" not in definition  # cloning renames cleanly via parse_definition
    assert definition["cube"] == "Plan1"
    assert [am["dimension"] for am in definition["rows"]] == ["Account"]
    assert definition["rows"][0]["selection"] == {"type": "children", "member": "Account"}
    assert definition["columns"][0]["selection"] == {"type": "range", "start": "Jan", "end": "Dec"}
    assert definition["businessRuleAssociations"][0]["ruleName"] == "Calc All"

    # cube-folder entry: cube comes from the path
    assert forms["Cash Detail"]["cube"] == "Plan1"
    assert forms["Cash Detail"]["data"]["definition"]["rows"]

    # the shipped dump round-trips into a valid clone spec
    clone = parse_definition(definition, "Rolling Forecast Copy")
    assert clone.name == "Rolling Forecast Copy"
    assert clone.rows[0].selection.member == "Account"

    sections = {s.name: s for s in bundle.sections}
    assert sections["Forms"].status == "complete"
    assert sections["Forms"].count == 2


def test_malformed_definition_is_an_issue_plus_name_only_record():
    files = _base_files()
    files[f"{_GLOBAL_FORMS}/Rolling Forecast.xml"] = render_xml(_form_spec("Rolling Forecast"))
    files[f"{_GLOBAL_FORMS}/Broken.xml"] = '<form name="Broken"'  # truncated XML
    files[f"{_GLOBAL_FORMS}/NotAForm.xml"] = "<somethingElse/>"  # wrong root element
    bundle = analyze_snapshot(_zip_bytes(files))

    # the snapshot parse never aborts: the good form and the dimensions survived
    assert bundle.analysis.application == _APP
    assert bundle.analysis.counts["members"] == 2
    assert any("Broken.xml" in i for i in bundle.analysis.issues)
    assert any("NotAForm.xml" in i for i in bundle.analysis.issues)

    forms = _forms(bundle)
    assert "definition" in forms["Rolling Forecast"]["data"]
    for name in ("Broken", "NotAForm"):
        assert forms[name]["data"]["name"] == name
        assert "definition" not in forms[name]["data"]
    sections = {s.name: s for s in bundle.sections}
    assert sections["Forms"].status == "complete"  # at least one definition parsed
    assert sections["Forms"].count == 3


def test_all_definitions_malformed_marks_forms_partial():
    files = _base_files()
    files[f"{_GLOBAL_FORMS}/Broken.xml"] = '<form name="Broken"'
    bundle = analyze_snapshot(_zip_bytes(files))
    sections = {s.name: s for s in bundle.sections}
    assert sections["Forms"].status == "partial"
    assert sections["Forms"].note == snapshot_mod._FORMS_UNPARSED_NOTE
    assert _forms(bundle)["Broken"]["data"].get("definition") is None


def test_nav_flow_stub_deduped_against_parsed_definition():
    files = _base_files()
    files[f"{_NAV_FLOWS}/Admin.xml"] = _NAV_FLOW
    files[f"{_GLOBAL_FORMS}/Rolling Forecast.xml"] = render_xml(_form_spec("Rolling Forecast"))
    bundle = analyze_snapshot(_zip_bytes(files))

    rolling = [r for r in bundle.records if r["kind"] == "form" and r["name"] == "Rolling Forecast"]
    assert len(rolling) == 1  # definition wins; no referenced-only duplicate
    assert "definition" in rolling[0]["data"]
    assert not rolling[0]["data"].get("referencedOnly")
    # the dashboard reference had no definition, so its stub is kept
    dashboard = _forms(bundle)["Summary Dashboard"]["data"]
    assert dashboard["referencedOnly"] is True
    # references are still counted even when the stub is deduped
    assert bundle.analysis.counts["formsReferenced"] == 1
    assert bundle.analysis.counts["dashboardsReferenced"] == 1


def test_references_only_snapshot_stays_derived():
    files = _base_files()
    files[f"{_NAV_FLOWS}/Admin.xml"] = _NAV_FLOW
    bundle = analyze_snapshot(_zip_bytes(files))
    sections = {s.name: s for s in bundle.sections}
    assert sections["Forms"].status == "derived"
    assert sections["Forms"].note == snapshot_mod._FORMS_REFERENCED_NOTE
    assert "forms" not in bundle.analysis.counts
    assert all(r["data"].get("referencedOnly") for r in bundle.records if r["kind"] == "form")


def test_unparseable_definition_still_wins_over_nav_flow_stub(session):
    # Real Oracle form XML doesn't parse via the EPM Wizard parser, so on a
    # genuine snapshot the definition file is present-but-unparsed AND the form
    # is referenced by a nav flow. The file record (with cube/folder) must win —
    # a bare referencedOnly stub must never overwrite it in build_tenant_metadata.
    proj = projects_svc.create_project(session, "SnapFormStubRegression")
    files = _base_files()
    files[f"{_HP}/resource/Cube/Plan1/Data Forms/Rolling Forecast.xml"] = "<oracle:form/>"  # won't parse
    files[f"{_NAV_FLOWS}/Admin.xml"] = _NAV_FLOW  # references "Rolling Forecast"
    bundle = analyze_snapshot(_zip_bytes(files))

    rolling = [r for r in bundle.records if r["kind"] == "form" and r["name"] == "Rolling Forecast"]
    assert len(rolling) == 1  # no duplicate stub
    assert rolling[0]["data"].get("referencedOnly") is not True
    assert rolling[0]["data"]["cube"] == "Plan1"  # file-derived cube preserved

    cv = merge_snapshot_into_context(session, proj.id, bundle, standalone=True)
    session.flush()
    record = context_store.build_tenant_metadata(session, cv.id).forms["rolling forecast"]
    assert record.cube == "Plan1"  # not clobbered by a cube=None stub


# --- merged context: definition feeds reference-form cloning ---------------------


def test_build_tenant_metadata_surfaces_definition_for_cloning(session):
    proj = projects_svc.create_project(session, "SnapFormDefs")
    files = _base_files()
    files[f"{_GLOBAL_FORMS}/Rolling Forecast.xml"] = render_xml(_form_spec("Rolling Forecast"))
    cv = merge_snapshot_into_context(session, proj.id, analyze_snapshot(_zip_bytes(files)),
                                     standalone=True)
    session.flush()

    md = context_store.build_tenant_metadata(session, cv.id)
    record = md.forms["rolling forecast"]
    assert record.definition is not None
    assert record.definition["rows"][0]["dimension"] == "Account"

    # the existing "like <form>" path seeds the spec from the snapshot definition
    spec, inferences, _questions = build_initial_spec("Build a copy like Rolling Forecast", md, _APP)
    assert spec.reference_template is not None
    assert spec.reference_template.name == "Rolling Forecast"
    assert spec.name != "Rolling Forecast"
    assert spec.cube == "Plan1"
    assert spec.rows[0].dimension == "Account"
    assert spec.rows[0].selection.type == "children"
    assert "Reference form: Rolling Forecast" in inferences
