"""Deterministic EPM Automate script generation for a recorded deployment.

Generates the *equivalent* command script for what a deployment did
(login -> uploadfile -> importsnapshot -> logout) as plain text. The script is
never executed by EPM Wizard — this module only renders text. Credentials are
never embedded: authentication uses environment-variable placeholders and an
encrypted ``.epw`` password file, per Oracle's recommended practice.
"""

from __future__ import annotations

from pathlib import Path

from sqlalchemy.orm import Session

from ..db.models import Artifact, Deployment
from . import iso

SCRIPT_FORMATS = ("sh", "ps1")


def _package_artifact(session: Session, deployment: Deployment) -> Artifact | None:
    """The package artifact persisted by the deployment pipeline (matched by checksum)."""
    if not deployment.checksum:
        return None
    return (
        session.query(Artifact)
        .filter_by(project_id=deployment.project_id, kind="package", checksum=deployment.checksum)
        .order_by(Artifact.created_at.desc())
        .first()
    )


def _package_filename(deployment: Deployment, artifact: Artifact | None) -> str:
    if artifact is not None and artifact.path:
        return Path(artifact.path).name
    # Same naming rule the deployment pipeline uses when writing the package.
    return f"{deployment.artifact_name.replace(' ', '_')}_{(deployment.checksum or '')[:12]}.zip"


def _header_lines(deployment: Deployment, package_file: str, comment: str) -> list[str]:
    return [
        f"{comment} EPM Automate script generated by EPM Wizard",
        f"{comment} Deployment: {deployment.id}",
        f"{comment} Recorded at: {iso(deployment.created_at)}",
        f"{comment} Artifact: {deployment.artifact_name} ({deployment.artifact_type}, operation {deployment.operation})",
        f"{comment} Application: {deployment.application or '-'}",
        f"{comment} Environment: {deployment.environment_name or '-'} ({deployment.classification})",
        f"{comment} Package file: {package_file}",
        f"{comment} Package checksum (sha256): {deployment.checksum or 'unknown'}",
        f"{comment} Credentials are NEVER embedded: set the environment variables below",
        f"{comment} and point EPM_PASSWORD_FILE at an encrypted .epw file (epmautomate encrypt).",
    ]


def _sh_script(deployment: Deployment, package_file: str) -> str:
    snapshot = package_file.removesuffix(".zip")
    lines = [
        "#!/usr/bin/env bash",
        *_header_lines(deployment, package_file, "#"),
        "",
        "set -euo pipefail",
        "",
        'EPM_URL="${EPM_URL:?Set EPM_URL to the target Oracle EPM environment URL}"',
        'EPM_USER="${EPM_USER:?Set EPM_USER to the deploying user}"',
        'EPM_PASSWORD_FILE="${EPM_PASSWORD_FILE:?Set EPM_PASSWORD_FILE to an encrypted .epw file path}"',
        "",
        "# Always log out, even when a command fails.",
        "trap 'epmautomate logout || true' EXIT",
        "",
        'epmautomate login "$EPM_USER" "$EPM_PASSWORD_FILE" "$EPM_URL"',
        f'epmautomate uploadfile "{package_file}"',
        f'epmautomate importsnapshot "{snapshot}"',
        "",
    ]
    return "\n".join(lines)


def _ps1_script(deployment: Deployment, package_file: str) -> str:
    snapshot = package_file.removesuffix(".zip")
    lines = [
        *_header_lines(deployment, package_file, "#"),
        "",
        '$ErrorActionPreference = "Stop"',
        "",
        'if (-not $env:EPM_URL) { throw "Set EPM_URL to the target Oracle EPM environment URL" }',
        'if (-not $env:EPM_USER) { throw "Set EPM_USER to the deploying user" }',
        'if (-not $env:EPM_PASSWORD_FILE) { throw "Set EPM_PASSWORD_FILE to an encrypted .epw file path" }',
        "",
        "try {",
        "    epmautomate login $env:EPM_USER $env:EPM_PASSWORD_FILE $env:EPM_URL",
        f'    epmautomate uploadfile "{package_file}"',
        f'    epmautomate importsnapshot "{snapshot}"',
        "}",
        "finally {",
        "    epmautomate logout",
        "}",
        "",
    ]
    return "\n".join(lines)


def build_script(session: Session, deployment: Deployment, fmt: str) -> str:
    """Render the deployment as an EPM Automate script. ``fmt`` is 'sh' or 'ps1'."""
    if fmt not in SCRIPT_FORMATS:
        raise ValueError(f"unsupported script format '{fmt}' (expected one of: {', '.join(SCRIPT_FORMATS)})")
    package_file = _package_filename(deployment, _package_artifact(session, deployment))
    return _sh_script(deployment, package_file) if fmt == "sh" else _ps1_script(deployment, package_file)
