"""initial schema

Revision ID: 24c767b4fc2d
Revises: 
Create Date: 2026-07-17 15:33:31.764426
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '24c767b4fc2d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('operation_class', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=300), nullable=True),
    sa.Column('environment', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_records_project_id'), ['project_id'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active_environment_id', sa.String(length=32), nullable=True),
    sa.Column('active_context_version_id', sa.String(length=32), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_profiles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider_type', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=400), nullable=True),
    sa.Column('default_model', sa.String(length=120), nullable=True),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('role_models', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('has_key', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'project_id', 'key', name='uq_setting')
    )
    op.create_table('artifacts',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=600), nullable=True),
    sa.Column('checksum', sa.String(length=80), nullable=True),
    sa.Column('context_version', sa.String(length=60), nullable=True),
    sa.Column('source_conversation_id', sa.String(length=32), nullable=True),
    sa.Column('source_message_id', sa.String(length=32), nullable=True),
    sa.Column('parent_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('checksum', sa.String(length=80), nullable=True),
    sa.Column('text_extract', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_versions',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('environment_id', sa.String(length=32), nullable=True),
    sa.Column('application', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=True),
    sa.Column('path', sa.String(length=600), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('environment_name', sa.String(length=120), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('application', sa.String(length=120), nullable=True),
    sa.Column('artifact_name', sa.String(length=200), nullable=False),
    sa.Column('artifact_type', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('operation_class', sa.String(length=20), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approval_note', sa.String(length=400), nullable=True),
    sa.Column('context_version', sa.String(length=60), nullable=True),
    sa.Column('spec_version', sa.String(length=30), nullable=True),
    sa.Column('checksum', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('job_result', sa.String(length=60), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.JSON(), nullable=False),
    sa.Column('backup_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_profiles',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=400), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('auth_method', sa.String(length=40), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('preferred_application', sa.String(length=120), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_context_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('remember_credentials', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_executions',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('application', sa.String(length=120), nullable=True),
    sa.Column('cube', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prompt_values', sa.JSON(), nullable=False),
    sa.Column('job_id', sa.String(length=120), nullable=True),
    sa.Column('job_result', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_records',
    sa.Column('context_version_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('dimension', sa.String(length=120), nullable=True),
    sa.Column('application', sa.String(length=120), nullable=True),
    sa.Column('cube', sa.String(length=120), nullable=True),
    sa.Column('alias', sa.String(length=300), nullable=True),
    sa.Column('parent', sa.String(length=300), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['context_version_id'], ['context_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_records_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_project_id'), ['project_id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('process_steps', sa.JSON(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('skill', sa.String(length=60), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_states',
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('skill', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_states_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_states_project_id'))

    op.drop_table('workflow_states')
    op.drop_table('messages')
    with op.batch_alter_table('context_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_context_records_name'))
        batch_op.drop_index(batch_op.f('ix_context_records_kind'))
        batch_op.drop_index(batch_op.f('ix_context_records_dimension'))

    op.drop_table('context_records')
    op.drop_table('rule_executions')
    op.drop_table('environment_profiles')
    op.drop_table('deployments')
    op.drop_table('conversations')
    op.drop_table('context_versions')
    op.drop_table('attachments')
    op.drop_table('artifacts')
    op.drop_table('settings')
    op.drop_table('provider_profiles')
    op.drop_table('projects')
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_project_id'))

    op.drop_table('audit_records')
    # ### end Alembic commands ###
