#!/usr/bin/env bash
# Register the oauth2-proxy callback URL in App ID's redirect-URL allowlist.
# Run ONCE after the first ./deploy-code-engine.sh created the epmw-auth app
# (its URL is generated by Code Engine, so terraform cannot know it upfront).
# Idempotent: re-running replaces the allowlist with the current URL set.
#
# Prereqs: ibmcloud CLI logged in; curl; the terraform outputs available
# (run from this directory, or pass APPID_TENANT explicitly).
#
# Usage:
#   REGION=us-south ./configure-app-id.sh
#   APPID_TENANT=<tenant-guid> REGION=us-south ./configure-app-id.sh

set -euo pipefail

REGION="${REGION:-us-south}"
APPID_TENANT="${APPID_TENANT:-$(terraform -chdir="$(dirname "$0")/terraform" output -raw app_id_tenant_id)}"

AUTH_URL="$(ibmcloud ce app get --name epmw-auth --output json \
  | grep -o '"url": *"https[^"]*"' | head -1 | sed 's/.*: *"//;s/"//')"
if [ -z "${AUTH_URL}" ]; then
  echo "error: could not read the epmw-auth app URL — deploy it first" >&2
  exit 1
fi

TOKEN="$(ibmcloud iam oauth-tokens --output json | grep -o '"iam_token": *"[^"]*"' | sed 's/.*: *"//;s/"//')"
MGMT="https://${REGION}.appid.cloud.ibm.com/management/v4/${APPID_TENANT}"

echo "==> Registering ${AUTH_URL}/oauth2/callback in App ID ${APPID_TENANT}"
curl -fsS -X PUT "${MGMT}/config/redirect_uris" \
  -H "Authorization: ${TOKEN}" -H "Content-Type: application/json" \
  -d "{\"redirectUris\": [\"${AUTH_URL}/oauth2/callback\"]}"

echo
echo "==> Done. Invite users: IBM Cloud console -> App ID -> Cloud Directory -> Users."
echo "    Your site (login-gated): ${AUTH_URL}"
